// <auto-generated />
using GeekHunter.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeekHunter.Migrations
{
    [DbContext(typeof(GeekHunterContext))]
    partial class GeekHunterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("GeekHunter.Model.Candidate", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("GeekHunter.Model.CandidateSkill", b =>
                {
                    b.Property<long>("CandidateId");

                    b.Property<long>("SkillId");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkill");
                });

            modelBuilder.Entity("GeekHunter.Model.Skill", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("GeekHunter.Model.CandidateSkill", b =>
                {
                    b.HasOne("GeekHunter.Model.Candidate", "Candidate")
                        .WithMany("Skill")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeekHunter.Model.Skill", "Skill")
                        .WithMany("Candidates")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
